2021-09-22T08:02:20.458734+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-09-22T08:02:20.458743+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-09-22T08:02:20.458886+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)
2021-09-22T08:02:20.458887+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-09-22T08:02:20.459335+00:00 app[worker.1]:     __import__(pkg_name)
2021-09-22T08:02:20.459335+00:00 app[worker.1]:   File "/app/InlineBot/__init__.py", line 24, in <module>
2021-09-22T08:02:20.459335+00:00 app[worker.1]:     raise Exception("Your Admins list does not contain valid integers.")
2021-09-22T08:02:20.459336+00:00 app[worker.1]: Exception: Your Admins list does not contain valid integers.
2021-09-22T08:02:20.597618+00:00 heroku[worker.1]: Process exited with status 1
2021-09-22T08:02:20.684784+00:00 heroku[worker.1]: State changed from up to crashed